// filename: aiService.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
const API_URL = `${import.meta.env.VITE_BACKEND_URL}/api/ai`;

// Streams a recipe from the backend (which proxies to Gemini).
// Calls onChunk with each new piece of text as it arrives.
export async function streamRecipe(
  prompt: string,
  onChunk: (text: string) => void,
): Promise<void> {
  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt }),
  });

  // Non-200 (e.g. 504 timeout, 400, 500) -> read the JSON error if present.
  if (!res.ok) {
    let message = `API error: ${res.status}`;
    try {
      const body = await res.json();
      if (body?.error) message = body.error;
    } catch {
      // body wasn't JSON; keep the status-based message
    }
    throw new Error(message);
  }

  const reader = res.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let errorEvent = false; // set when the previous line was "event: error"

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line) continue;

      // Backend signals a mid-stream failure with: event: error \n data: {...}
      if (line.startsWith("event:")) {
        errorEvent = line.slice(6).trim() === "error";
        continue;
      }

      if (!line.startsWith("data:")) continue;
      const data = line.slice(5).trim();
      if (!data) continue;

      if (errorEvent) {
        let message = "AI stream interrupted";
        try {
          const parsed = JSON.parse(data);
          if (parsed?.error) message = parsed.error;
        } catch {
          // leave default message
        }
        throw new Error(message);
      }

      try {
        const parsed = JSON.parse(data);
        const text = parsed.candidates?.[0]?.content?.parts?.[0]?.text;
        if (text) onChunk(text);
      } catch {
        // Ignore incomplete chunks (a chunk boundary can split a data: line)
      }
    }
  }
}